In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'1.5.3'

In [3]:
df = pd.read_csv('housing.csv')

In [4]:
len(df.columns)

10

In [5]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [6]:
df.ocean_proximity.nunique()

5

In [7]:
df.groupby('ocean_proximity')['median_house_value'].mean()['NEAR BAY']

259212.31179039303

In [8]:
tb_mean = df.total_bedrooms.mean()
tb_mean

537.8705525375618

In [9]:
df.total_bedrooms.fillna(tb_mean, inplace=True)

In [10]:
df.total_bedrooms.mean()

537.8705525375617

In [11]:
island_options = df[df['ocean_proximity'] == 'ISLAND']
island_options

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [12]:
selected_columns = island_options[['housing_median_age', 'total_rooms', 'total_bedrooms']]
selected_columns

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [13]:
X = selected_columns.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [14]:
XTX = X.T.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [15]:
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [16]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [17]:
w = XTX_inverse.dot(X.T).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [18]:
last_element_of_w = w[-1]
last_element_of_w

5.699229455065575